### ISSUE TITLE
Slider handle offset

### ISSUE THREAD

**Issue by fabiancook** [themre/roundy#1]
Hi, I have found that the slider handle is offset

![image](https://user-images.githubusercontent.com/4337080/37120045-1ad9a3c0-22be-11e8-93bb-987da591fb0b.png)
![image](https://user-images.githubusercontent.com/4337080/37120052-1f1e070a-22be-11e8-91b2-d84bce468fe5.png)

I am able to correct this by doing two things:

- Setting the width of the container to the same as the svg
- Setting the slider handle to be a container, with the indicator being positioned inside this container

I got it working by using...

```
.graph-circle-slider .sliderHandle {
  width: <size>px;
  height: <size>px;
  top: 0;
  left: 0;
  transform-origin: 50% 50%;
}

.graph-circle-slider .sliderHandle:after {
  content: '';
  display: block;
  width: 20px;
  height: 20px;
  border-radius: 100%;
  position: absolute;
  top: calc(50% - 10px);
  right: 0;
  background: linear-gradient(to top,#fff,#f2f2f2);
  border: 1px solid #ccc;
  transform: all ease 0.4s;
  box-sizing: border-box;
}
```

You'll notice the handle is also now contained within the slider circle, you could change this by changing the offset to be negative and increasing the width, or by removing `box-sizing`

![image](https://user-images.githubusercontent.com/4337080/37120192-945c51de-22be-11e8-9d5b-540aa668e3a6.png)

Let me know what you think

PS. Thanks for making this, its a life saver

**Comment by themre** [comment]
yeah this offset of the handle needs to be sorted. I left escape hatch with `overrideStyle` so anyone can position it properly. perhaps the best way is to calculate it from radius and strokeWidth and position it on its center.

**Comment by fabiancook** [comment]
Would the radius always be half the amount of the width? If so you can auto-calculate the box using that (That's all I am doing).

**Comment by themre** [comment]
I've implemented style to calculate thumb offset based on strokeWidth and thumbSize (new prop added, default is 20). can you test it and please let me know if it's ok? btw, sorry for long response, had a busy week.

**Comment by themre** [comment]
will close for now.
