### ISSUE TITLE
onAfterChange is triggered when clicking anywhere on the page

### ISSUE THREAD

**Issue by camillomalnati** [themre/roundy#11]
this can also be observed in the demo if you add a console.log in the onAfterChange function and can create problem as the call is not expected if the click is outside the slider.

**Comment by themre** [comment]
sorry for late response, I was away for a while. I will have a look at it this week. thanks for this report!

**Comment by themre** [comment]
I published 2.0.6 version with fix for firing callbacks everywhere. please take a look and report if there are any problems. demo can be seen here: https://codesandbox.io/s/xr49zz904o
