### ISSUE TITLE
Implement over-rotation

### ISSUE THREAD

**Issue by fabiancook** [themre/roundy#2]
It would be good if when the user has rotated the full 360 degrees that we have the option to either:

- Stop rotating, so if the user wants 0, they have to rotate back
- Stack layers, so that we can go past "max" and continue rotating around and around, each time changing the colour of the rotation indicator, maybe if we used a gradient for the indicator it would work better. 

Let me know your thoughts

**Comment by themre** [comment]
hi,
yeah, preventing the user to go past max value was something I was aware of but didn't implement it yet. probably we need to check something like this `delta x > 0 && angle === 0` then don't update value. and viceversa to go from 0 to 360.

**Comment by themre** [comment]
I released new version, 2.0.1 with breaking changes. but now it handles flipping on min and max value. so if user goes to 0, it doesn't flip to 360 if it goes across. instead it holds value to 0 for some distance and goes to e.g. 330 if user has gone much further. the same goes for 360 -> 0. for over rotation if was a bit too much work :)

**Comment by fabiancook** [comment]
Thank you. I think this can now be closed.
