### ISSUE TITLE
Sliced prop not working properly on Firefox

### ISSUE THREAD

**Issue by Luka-G** [themre/roundy#3]
@themre 
On Firefox, when using sliced={true}, only one breakpoint is shown. Please, check the screenshot:

![test](https://user-images.githubusercontent.com/17803603/46213360-a514f880-c338-11e8-8b6e-209cc5471243.png)

**Comment by themre** [comment]
Thanks for PR! demo available here: https://codesandbox.io/s/8491415979

**Comment by themre** [comment]
This is fixed in 1.0.4 version.
