### ISSUE TITLE
Clickable Slider

### ISSUE THREAD

**Issue by kcatstack** [themre/roundy#5]
It's not really an issue but a request for a feature.
Instead of requiring users to drag the knob, it's would be handy to detect click and set slider value at the position users click.
Thanks.

Edit: Currently, I am able to implement it using `onClick` on roundy's parent

```
  handleClick(event) {
    const { offsetY, offsetX } = event.nativeEvent;

    const distanceFromCenter = Math.sqrt((offsetY - RADIUS)**2 + (offsetX - RADIUS)**2);

    if (distanceFromCenter > RADIUS - WIDTH && distanceFromCenter < RADIUS) {
      const angle = Math.atan2(offsetY - (RADIUS - WIDTH)/2, offsetX - RADIUS);
      const newValue = Math.round(Math.abs(angle * 100 / Math.PI));
      // setState or do smth with newValue here
    }
  }

render() {
  <div onClick={this.handleClick}>
    <Roundy
      min={0}
      max={100}
      radius={RADIUS}
      strokeWidth={WIDTH}
     />
  </div>
}
```

**Comment by themre** [comment]
I released new version, 2.0.1 which has `allowClick` prop that allows clicking on slider. I used to prevent this since I needed stacked sliders and haven't done checking on svg. maybe I'll do this next time. for now you can try it here: https://codesandbox.io/s/xr49zz904o
