### ISSUE TITLE
Pie round slider

### ISSUE THREAD

**Issue by itsmichaeldiego** [themre/roundy#6]
Hey, hello everyone, first thank you for the library, is super useful.

I have the requirement of doing the slider like a pie slider, something like this:

<img width="204" alt="screen shot 2018-11-15 at 3 52 02 pm" src="https://user-images.githubusercontent.com/6419886/48560581-6dfda500-e8ee-11e8-96fd-44575acd2889.png">

I see this library does not offer a way to do it, but I am wondering if it would be easy to modify the slider on my fork to be able to do this, and if so, if you could point me in the right direction on how to do this.

Thanks in advance.

**Comment by themre** [comment]
hi, glad you like the library, i wasn't sure anyone will use it :) I guess you need to reimplement jquery round slider... so probably best start is to look here: https://github.com/soundar24/roundSlider/blob/master/src/roundslider.js
I would probably start with svg to cut it with desired angle. then you also need to make sure where is starting point. in my lib start point is on top, here it will be on left bottom.

currently i'm a little busy, but will try to help you with any way possible. looking forward with what you come up.

**Comment by itsmichaeldiego** [comment]
@themre Actually the picture I shared was from roundSlider, I am currently using that one as is the only one that has this type of "pie" library, so I would go with this one as for now, and switch for yours if you ever make this change, as your library is way more straight-forward, simple and lightweight.

**Comment by themre** [comment]
I released new version with breaking changes (2.0.1). Set up small demo: https://codesandbox.io/s/xr49zz904o
Please let me know if works ok.

**Comment by itsmichaeldiego** [comment]
@themre Seems to work man! Thanks! Should we add it to the Readme?

**Comment by themre** [comment]
Glad it works. Yeah, I will add more examples to the readme, thanks!

**Comment by themre** [comment]
added and also created some examples on codesandbox: https://codesandbox.io/s/xr49zz904o

**Comment by itsmichaeldiego** [comment]
Thanks @themre
